plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

repositories {
    mavenCentral()
    mavenLocal()

    // Create, Ponder, Flywheel
    maven { url = "https://maven.createmod.net" }

    // Registrate
    maven { url = "https://maven.ithundxr.dev/mirror" }

    // ForgeConfigAPIPort
    maven { url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/" }
}

minecraft {
    mappings channel: mapping_channel, version: mapping_version

    runs {
        client {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        gameTestServer {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            args '--mod', mod_id,
                    '--all',
                    '--output', file('src/generated/resources/'),
                    '--existing', file('src/main/resources/')

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

dependencies {
    // Minecraft + Forge
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    // Create
    implementation(fg.deobf(
            "com.simibubi.create:create-${minecraft_version}:${create_version}:slim"
    )) {
        transitive = false
    }

    // Ponder
    implementation(fg.deobf(
            "net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}"
    ))

    // Flywheel
    compileOnly(fg.deobf(
            "dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version}"
    ))

    runtimeOnly(fg.deobf(
            "dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version}"
    ))

    // Registrate
    implementation(fg.deobf(
            "com.tterrag.registrate:Registrate:${registrate_version}"
    ))
    // MixinExtras
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.4.1"))
    implementation("io.github.llamalad7:mixinextras-forge:0.4.1")
}

processResources {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version          : forge_version,
            forge_version_range    : forge_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license             : mod_license,
            mod_version             : mod_version,
            mod_authors             : mod_authors,
            mod_description        : mod_description
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml']) {
        expand replaceProperties
    }

    duplicatesStrategy = DuplicatesStrategy.WARN
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            url = "file://${project.projectDir}/repo"
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}